### ISSUE TITLE
Dockerfile MAINTAINER instruction is deprecated

### ISSUE THREAD

**Issue by davbrito** [davbrito/t3gp-server#1]
According to [Docker reference](https://docs.docker.com/engine/reference/builder/#maintainer-deprecated) the `MAINTAINER` instructon is deprecated and should be replaced by the `LABEL` instruction.

> The `MAINTAINER` instruction sets the Author field of the generated images. The `LABEL` instruction is a much more flexible version of this and you should use it instead, as it enables setting any metadata you require, and can be viewed easily, for example with docker inspect. To set a label corresponding to the `MAINTAINER` field you could use:
> ```Dockerfile
> LABEL maintainer="SvenDowideit@home.org.au"
> ```
> This will then be visible from docker inspect with the other labels.

**Comment by alfosuag** [comment]
Oie siiiii :v
